package com.busanit501.androidlabtest501.ch11_jetpack.recyclerview.test1simple

import androidx.recyclerview.widget.RecyclerView
import com.busanit501.androidlabtest501.databinding.Ch11ItemSimpleRecycler2Binding
import com.busanit501.androidlabtest501.databinding.Ch11ItemSimpleRecycler3Binding
import com.busanit501.androidlabtest501.databinding.Ch11ItemSimpleRecycler4Binding
import com.busanit501.androidlabtest501.databinding.Ch11ItemSimpleRecyclerBinding

class Ch11MyViewHolder4(val binding: Ch11ItemSimpleRecycler4Binding): RecyclerView.ViewHolder(binding.root) {
}